stages:
  - build
  - deploy_master

image: node:lts-alpine

build:
  tags:
    - permanent-recall-frontend
  stage: build
  # variables:
  #   GIT_SUBMODULE_STRATEGY: recursive
  script:
    - yarn install
    - yarn private:generate
  artifacts:
    paths:
      - dist
  only:
    - master

deploy_master:
  image: "registry.gitlab.com/bicodetech/permanent-recall-frontend"
  tags:
    - permanent-recall-frontend
  stage: deploy_master
  script:
    - bash deploy/deploy.sh
  dependencies:
    - build
  only:
    - master
