stages:
  - build
  - deploy_master

# image: node:lts

# build:
#   tags:
#     - permanent-recall-frontend
#   stage: build
#   # variables:
#   #   GIT_SUBMODULE_STRATEGY: recursive
#   script:
#     - yarn install
#     - yarn generate
#   artifacts:
#     paths:
#       - dist
#   only:
#     - master

deploy_master:
  tags:
    - permanent-recall-frontend
  stage: deploy_master
  script:
    - echo 'test echo'
    - ls pipeline-lib
    - cat pipeline-lib/deploy.sh
    - bash pipeline-lib/deploy.sh master ${CI_REPOSITORY_URL}
  # dependencies:
  #   - build
  only:
    - master
